### ISSUE TITLE
I can't compile current version

### ISSUE THREAD

**Issue by vvtx** [siemens/freertos-cell#2]
I've tried to compile current version and I get following errors:

> make
arm-linux-gnueabihf-gcc    -c -o freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.o freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S: Assembler messages:
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:215: Error: selected processor does not support `fmrxne R1,FPSCR' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:215: Error: selected processor does not support `vpushne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:218: Error: selected processor does not support `vpopne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:218: Error: selected processor does not support `vmsrne FPSCR,R0' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:228: Error: selected processor does not support `vpopne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:228: Error: selected processor does not support `vmsrne FPSCR,R0' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:320: Error: selected processor does not support `fmrxne R1,FPSCR' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:320: Error: selected processor does not support `vpushne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:331: Error: selected processor does not support `vpopne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:331: Error: selected processor does not support `vmsrne FPSCR,R0' in ARM mode
make: *** [<builtin>: freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.o] Error 1

How to fix it?

**Comment by johann-pfefferl** [comment]
Hello

What Compiler Version do you use?

arm-linux-gnueabihf-gcc --version

Mit freundlichen Grüßen
  Dr. Johann Pfefferl
----

Siemens AG
Corporate Technology
Research & Technology Center
CT RDA IOT SES-DE
Otto-Hahn-Ring 6
81739 Muenchen, Germany
mailto: johann.pfefferl@siemens.com
phone: +49 1520 3450 138
fax:   +49 89 636 33045
_____________________________________________________
SIEMENS AG: Chairman of the Supervisory Board: Jim Hagemann Snabe
Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer
Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Cedrik Neike,
Michael Sen, Ralf P. Thomas
Registered offices: Berlin and Munich, Germany
Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684
WEEE-Reg.-No. DE 23691322

________________________________
Von: vvtx <notifications@github.com>
Gesendet: Sonntag, 23. September 2018 10:35
An: siemens/freertos-cell
Cc: Subscribed
Betreff: [siemens/freertos-cell] I can't compile current version (#2)


I've rtied to compile current version and I get following errors:

make
arm-linux-gnueabihf-gcc -c -o freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.o freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S: Assembler messages:
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:215: Error: selected processor does not support fmrxne R1,FPSCR' in ARM mode freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:215: Error: selected processor does not supportvpushne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:218: Error: selected processor does not support vpopne {D0-D15}' in ARM mode freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:218: Error: selected processor does not supportvmsrne FPSCR,R0' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:228: Error: selected processor does not support vpopne {D0-D15}' in ARM mode freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:228: Error: selected processor does not supportvmsrne FPSCR,R0' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:320: Error: selected processor does not support fmrxne R1,FPSCR' in ARM mode freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:320: Error: selected processor does not supportvpushne {D0-D15}' in ARM mode
freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:331: Error: selected processor does not support vpopne {D0-D15}' in ARM mode freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.S:331: Error: selected processor does not supportvmsrne FPSCR,R0' in ARM mode
make: *** [: freertos/Source/portable/GCC/ARM_A7jailhouse/portASM.o] Error 1

How to fix it?

**Comment by johann-pfefferl** [comment]
Hello

All the specified CFLAGS from the Makefile are vanished. Do you really use the provided Makefile to compile the whole thing?

Mit freundlichen Grüßen
  Dr. Johann Pfefferl
----

Siemens AG
Corporate Technology
Research & Technology Center
CT RDA IOT SES-DE
Otto-Hahn-Ring 6
81739 Muenchen, Germany
mailto: johann.pfefferl@siemens.com
phone: +49 1520 3450 138
fax:   +49 89 636 33045
_____________________________________________________
SIEMENS AG: Chairman of the Supervisory Board: Jim Hagemann Snabe
Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer
Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Cedrik Neike,
Michael Sen, Ralf P. Thomas
Registered offices: Berlin and Munich, Germany
Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684
WEEE-Reg.-No. DE 23691322

________________________________

**Comment by vvtx** [comment]
My gcc version is: 
> arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Arch Repository) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Regarding the second question - yes I'm using the provided Makefile. To be honest I just run make in "freertos-cell" directory only.

**Comment by vvtx** [comment]
Temporarily I fixed the problem with following lines in Makefile:
.S.o:
        $(CC) $(CFLAGS) $< -c -o $@

**Comment by johann-pfefferl** [comment]
Hello

Have you set the environment variable CC in your shell?

What output shows the command

env CC

Mit freundlichen Grüßen
  Dr. Johann Pfefferl
----

Siemens AG
Corporate Technology
Research & Technology Center
CT RDA IOT SES-DE
Otto-Hahn-Ring 6
81739 Muenchen, Germany
mailto: johann.pfefferl@siemens.com
phone: +49 1520 3450 138
fax:   +49 89 636 33045
_____________________________________________________
SIEMENS AG: Chairman of the Supervisory Board: Jim Hagemann Snabe
Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer
Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Cedrik Neike,
Michael Sen, Ralf P. Thomas
Registered offices: Berlin and Munich, Germany
Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684
WEEE-Reg.-No. DE 23691322

________________________________

**Comment by vvtx** [comment]
Hello. I have no set CC environment variable at all.
